language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    packages:
      - libmysqlclient-dev
      - libperl-dev
      - libboost-dev
      - liblua5.1-0-dev
      - zlib1g-dev
      - uuid-dev
      - libssl-dev

script:
  - cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=ON -DEQEMU_ENABLE_BOTS=ON -DEQEMU_BUILD_LOGIN=ON
  - make -j2
  - ./bin/tests

trigger:
  event:
    exclude:
      - pull_request #avoid double build on PRs