language: cpp
compiler: gcc
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libmysqlclient-dev
    - libperl-dev
    - libboost-dev
    - liblua5.1-0-dev
    - zlib1g-dev
script:
  - CC=gcc-5 CXX=g++-5 cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=ON -DEQEMU_ENABLE_BOTS=ON
  - make -j8
  - ./bin/tests
branches:
  only:
    - master
    - stable
notifications:
  email: false
  irc:
    channels: "irc.eqemulator.net#eqemucoders"
os: linux
